title: Joe Kerhin
description: Simple homepage with GitHub Pages and Jekyll

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

include: [_pages]

collections:
  authors:
    output: true

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default
