theme: jekyll-theme-minimal
title: Joe Kerhin
description: Simple homepage with GitHub Pages and Jekyll

include: [_pages]

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default
